apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      initContainers:
      - name: init-nginxsrv
        image: busybox:1.28
        command: ['sh', '-c', "for i in {1..100}; do sleep 1; if nslookup nginx-svc; then exit 0; fi; done; exit 1"]