{
 "title": "Netology Красичков",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Free RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Load Average 1, 5, 15",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "AVG 1 min" },
    { "expr": "node_load5", "legendFormat": "AVG 5 min" },
    { "expr": "node_load15", "legendFormat": "AVG 15 min" }
   ]
  },
  {
   "title": "AVG нагрузка по всем ядрам CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(100 - (rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100))",
     "legendFormat": "AVG по всем ядрам"
    }
   ]
  },
  {
   "title": "Used /",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1-(node_filesystem_free_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}) + 0.04)",
     "legendFormat": "Used memory"
    }
   ]
  },
  {
   "title": "Свободно / Всего",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\"}) - ((node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_free_bytes{mountpoint=\"/\"}))",
     "legendFormat": "Available"
    },
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_free_bytes{mountpoint=\"/\"})",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}